/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	myingressv1beta1 "github.com/myoperator/k8saggregatorapiserver/pkg/apis/myingress/v1beta1"
	versioned "github.com/myoperator/k8saggregatorapiserver/pkg/client/clientset/versioned"
	internalinterfaces "github.com/myoperator/k8saggregatorapiserver/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/myoperator/k8saggregatorapiserver/pkg/client/listers/myingress/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MyIngressInformer provides access to a shared informer and lister for
// MyIngresses.
type MyIngressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.MyIngressLister
}

type myIngressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyIngressInformer constructs a new informer for MyIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyIngressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyIngressInformer constructs a new informer for MyIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1beta1().MyIngresses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1beta1().MyIngresses(namespace).Watch(context.TODO(), options)
			},
		},
		&myingressv1beta1.MyIngress{},
		resyncPeriod,
		indexers,
	)
}

func (f *myIngressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyIngressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myIngressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&myingressv1beta1.MyIngress{}, f.defaultInformer)
}

func (f *myIngressInformer) Lister() v1beta1.MyIngressLister {
	return v1beta1.NewMyIngressLister(f.Informer().GetIndexer())
}
