apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.apis.jtthink.com
spec:
  service:
    name: myapi # 注意这里需要和service相同
    namespace: default
    port: 8443
  group: apis.jtthink.com
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100